# SPDX-FileCopyrightText: 2025 cusy GmbH
#
# SPDX-License-Identifier: BSD-3-Clause

version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    cooldown:
      default-days: 10
    groups:
      github-actions:
        patterns:
          - "*"
